#!/bin/bash
set -e -u -o pipefail

. /app/date.sh --source-only

IP="$(dig +short $SERVER)"

echo "$SERVER" > /tmp/nordvpn_hostname

echo ########################################################
echo "$(adddate) INFO: Connection to server: $SERVER"
echo "$(adddate) INFO: Server IP: $IP"
echo "$(adddate) INFO: Protocol: $PROTOCOL"
echo ########################################################

cd /app/ovpn/config/ovpn_${PROTOCOL,,}

if [ -n "$SERVER" ]; then
  set -- "$@" '--config' "${SERVER}.${PROTOCOL,,}.ovpn"
else
  echo "$(adddate) ERROR: No OpenVPN config found in `pwd`/${SERVER}.${PROTOCOL,,}.ovpn. Exiting."
  exit 1
fi
if [ -n "$USERNAME" -a -n "$PASSWORD" ]; then
  echo "$USERNAME" > auth.conf
  echo "$PASSWORD" >> auth.conf
  chmod 600 auth.conf
  set -- "$@" '--auth-user-pass' 'auth.conf'
else
  echo "$(adddate) ERROR: No credentials available, please fill in the ENVIRONMENT variables USERNAME and PASSWORD. Exiting"
  exit 1
fi

openvpn "$@"